class Wage
    REGULAR_HOURLY_WAGE = 3.75
    EVENING_HOURLY_WAGE = 4.90
    REGULAR_WORK_HOURS = 8
    TWO_OVERTIME_HOURS = 2
    THREE_OVERTIME_HOURS = 3
    FOUR_OVERTIME_HOURS = 4
    EVENING_WAGE_START = "18:00"
    EVENING_WAGE_END = "6:00"
    REGULAR_WAGE_START = "06:00"
    REGULAR_WAGE_END = "18:00"
    MIDNIGHT = "00:00"
end